# Generated by Django 4.2 on 2023-06-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushQue', '0002_remove_pushnotification_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
