# Generated by Django 4.2 on 2023-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushQue', '0003_rename_datetime_pushnotification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='iter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
