# Generated by Django 4.2 on 2023-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end',
            field=models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True), null=True),
        ),
    ]
