# Generated by Django 4.2 on 2023-05-26 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
