# Generated by Django 4.2 on 2023-05-29 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
