# Generated by Django 4.2 on 2023-05-29 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
