# Generated by Django 4.2 on 2023-05-29 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_record_end_alter_record_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
