# Generated by Django 4.2 on 2023-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CUSTOMERUSER', 'Customeruser'), ('OWNERUSER', 'Owneruser')], default='CUSTOMERUSER', max_length=15),
        ),
    ]
